/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uI;

import static java.awt.SystemColor.desktop;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import uI.ClientForm;
import uI.Connexion;
import uI.Graphe;
import uI.OeuvreForm;
import uI.RechecheCa;
import uI.RechercheA;
import uI.StatistiqueFormm;
import uI.VenteForm;

/**
 *
 * @author HP
 */

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form NewMDIApplication
     */
    public Main() {
        initComponents();
        this.setTitle("Gestion d'atelier d'Art");
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        client = new javax.swing.JMenuItem();
        oeuvre = new javax.swing.JMenuItem();
        venteItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        categorieItem = new javax.swing.JMenuItem();
        artisteItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();
        contentMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        client.setMnemonic('o');
        client.setText("Client");
        client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientActionPerformed(evt);
            }
        });
        fileMenu.add(client);

        oeuvre.setMnemonic('s');
        oeuvre.setText("Oeuvre");
        oeuvre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oeuvreActionPerformed(evt);
            }
        });
        fileMenu.add(oeuvre);

        venteItem.setMnemonic('x');
        venteItem.setText("Vente");
        venteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venteItemActionPerformed(evt);
            }
        });
        fileMenu.add(venteItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Recherche");

        categorieItem.setMnemonic('t');
        categorieItem.setText("par catégorie");
        categorieItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorieItemActionPerformed(evt);
            }
        });
        editMenu.add(categorieItem);

        artisteItem.setMnemonic('y');
        artisteItem.setText("par artiste");
        artisteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artisteItemActionPerformed(evt);
            }
        });
        editMenu.add(artisteItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Statistique");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Top Artistes");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Ventes par artiste");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void venteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venteItemActionPerformed
         VenteForm vf =new VenteForm();
        desktopPane.add(vf);
        vf.setVisible(true);
    }//GEN-LAST:event_venteItemActionPerformed

    private void clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientActionPerformed
        // TODO add your handling code here: 
        ClientForm CC = new ClientForm();
        desktopPane.add(CC);
        CC.setVisible(true);
    }//GEN-LAST:event_clientActionPerformed

    private void categorieItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorieItemActionPerformed
        // TODO add your handling code here:
        RechecheCa Rc = new RechecheCa();
        desktopPane.add(Rc);
        Rc.setVisible(true);
    }//GEN-LAST:event_categorieItemActionPerformed

    private void artisteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artisteItemActionPerformed
        // TODO add your handling code here:
        RechercheA Ra = new RechercheA();
        desktopPane.add(Ra);
        Ra.setVisible(true);

    }//GEN-LAST:event_artisteItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        StatistiqueFormm Sf = new StatistiqueFormm();
        desktopPane.add(Sf);
        Sf.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void oeuvreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oeuvreActionPerformed
        // TODO add your handling code here:
        OeuvreForm ov =new OeuvreForm();
        desktopPane.add(ov);
        ov.setVisible(true);
    }//GEN-LAST:event_oeuvreActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        // TODO add your handling code here:

    // Créer une InternalFrame pour contenir le graphique
    javax.swing.JInternalFrame frame = new javax.swing.JInternalFrame(
            "Graphique des Ventes", true, true, true, true);
    
    // Ajouter ton JPanel Graphe dans la frame
    frame.setContentPane(new Graphe());
    
    frame.pack(); // Ajuste à la taille du contenu
    frame.setVisible(true);

    desktopPane.add(frame);
    try {
        frame.setSelected(true); // Active la fenêtre
    } catch (java.beans.PropertyVetoException e) {
        e.printStackTrace();
    }


    
    }//GEN-LAST:event_contentMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
          java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
         
        JFrame frame = new JFrame("Connexion");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        JDesktopPane desktop = new JDesktopPane();
        frame.setContentPane(desktop);
        frame.setSize(750,550);
        frame.setLocationRelativeTo(null);

        Connexion loginInternal = new Connexion();
        loginInternal.setSize(750,550); 
        loginInternal.setVisible(true);
        desktop.add(loginInternal);

        frame.setVisible(true);
    }
});

// affiche
        }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem artisteItem;
    private javax.swing.JMenuItem categorieItem;
    private javax.swing.JMenuItem client;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem oeuvre;
    private javax.swing.JMenuItem venteItem;
    // End of variables declaration//GEN-END:variables

}
