/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uI;

import entities.Oeuvre;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.OeuvreService;

/**
 *
 * @author HP
 */
public class OeuvreForm extends javax.swing.JInternalFrame {
     OeuvreService os =null;
     DefaultTableModel model = null;
     static int id ;
    /**
     * Creates new form OeuvreForm
     */
    public OeuvreForm() {
        initComponents();
        this.setTitle("Gestion d'oeuvres");
        os = new OeuvreService();
        model = (DefaultTableModel) ListeOeuvres.getModel();
        load();
    }
    public void load(){
        model.setRowCount(0);
        for( Oeuvre o : os.findAll()){
            model.addRow(new Object[]{
                o.getId(),
                o.getTitre(),
                o.getArtiste(),
                o.getCategorie(),
                o.getPrix()
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titre = new javax.swing.JLabel();
        artiste = new javax.swing.JLabel();
        categorie = new javax.swing.JLabel();
        prix = new javax.swing.JLabel();
        titretxt = new javax.swing.JTextField();
        artisteTxt = new javax.swing.JTextField();
        categorietxt = new javax.swing.JTextField();
        prixtxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        ajouterBn = new javax.swing.JButton();
        updateBn = new javax.swing.JButton();
        DeleteBn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListeOeuvres = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion des oeuvres", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(0, 51, 204))); // NOI18N

        titre.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        titre.setForeground(new java.awt.Color(102, 102, 255));
        titre.setText("Titre:");

        artiste.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        artiste.setForeground(new java.awt.Color(102, 102, 255));
        artiste.setText("Artiste:");

        categorie.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        categorie.setForeground(new java.awt.Color(102, 102, 255));
        categorie.setText("Catégorie:");

        prix.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        prix.setForeground(new java.awt.Color(102, 102, 255));
        prix.setText("Prix:");

        titretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titretxtActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        ajouterBn.setBackground(new java.awt.Color(0, 204, 0));
        ajouterBn.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        ajouterBn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uI/images/check_circle_17dp_1F1F1F_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        ajouterBn.setText("Ajouter");
        ajouterBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterBnActionPerformed(evt);
            }
        });

        updateBn.setBackground(new java.awt.Color(255, 255, 102));
        updateBn.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        updateBn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uI/images/edit_17dp_1F1F1F_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        updateBn.setText("Modifier");
        updateBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBnActionPerformed(evt);
            }
        });

        DeleteBn.setBackground(new java.awt.Color(255, 51, 51));
        DeleteBn.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        DeleteBn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uI/images/delete_17dp_1F1F1F_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        DeleteBn.setText("Suprimer");
        DeleteBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DeleteBn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateBn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ajouterBn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(ajouterBn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(updateBn)
                .addGap(50, 50, 50)
                .addComponent(DeleteBn)
                .addGap(62, 62, 62))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uI/images/add_to_queue_48dp_1F1F1F_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(categorie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(artiste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(prixtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(categorietxt)
                    .addComponent(artisteTxt)
                    .addComponent(titretxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(artisteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(artiste))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categorietxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categorie))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prixtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prix))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste des oeuvres", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        ListeOeuvres.setBackground(new java.awt.Color(153, 153, 255));
        ListeOeuvres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ListeOeuvres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Titre", "Artiste", "Catégorie", "Prix"
            }
        ));
        ListeOeuvres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListeOeuvresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListeOeuvres);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titretxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titretxtActionPerformed

    private void ajouterBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterBnActionPerformed
        // TODO add your handling code here:
        os .create(new Oeuvre(titretxt.getText(), artisteTxt.getText(), categorietxt.getText(), Double.parseDouble(prixtxt.getText())));
       
        
        load();
        
    }//GEN-LAST:event_ajouterBnActionPerformed

    private void ListeOeuvresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListeOeuvresMouseClicked
        // TODO add your handling code here:
         id =Integer.parseInt(model.getValueAt(ListeOeuvres.getSelectedRow(), 0).toString());
         titretxt.setText(model.getValueAt(ListeOeuvres.getSelectedRow(), 1).toString());
         artisteTxt.setText(model.getValueAt(ListeOeuvres.getSelectedRow(), 2).toString());
         categorietxt.setText(model.getValueAt(ListeOeuvres.getSelectedRow(), 3).toString());
         prixtxt.setText(model.getValueAt(ListeOeuvres.getSelectedRow(), 4).toString());
        
    }//GEN-LAST:event_ListeOeuvresMouseClicked

    private void DeleteBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBnActionPerformed
        // TODO add your handling code here:
         int reponse =JOptionPane.showConfirmDialog(this, "voulez vous vraiment supprimer cette oeuvre?");
          
        if(reponse ==0){
            os.delete(os.findById(id));
            load();
            vider();
        }
    }//GEN-LAST:event_DeleteBnActionPerformed

    private void updateBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBnActionPerformed
        // TODO add your handling code here:
          int reponse =JOptionPane.showConfirmDialog(this, "voulez vous vraiment modifier cette oeuvre?");
          
        if(reponse ==0){
         os.update(new Oeuvre(id,titretxt.getText(),artisteTxt.getText(),categorietxt.getText(),Double.parseDouble(prixtxt.getText())));
           load();
            vider();
    }//GEN-LAST:event_updateBnActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteBn;
    private javax.swing.JTable ListeOeuvres;
    private javax.swing.JButton ajouterBn;
    private javax.swing.JLabel artiste;
    private javax.swing.JTextField artisteTxt;
    private javax.swing.JLabel categorie;
    private javax.swing.JTextField categorietxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel prix;
    private javax.swing.JTextField prixtxt;
    private javax.swing.JLabel titre;
    private javax.swing.JTextField titretxt;
    private javax.swing.JButton updateBn;
    // End of variables declaration//GEN-END:variables

    private void vider() {
       titretxt.setText("");
        artisteTxt.setText("");
        categorietxt.setText("");
        prixtxt.setText("");    }
}
