/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uI;

import entities.Client;
import entities.Oeuvre;
import entities.VenteArt;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.ClientService;
import services.OeuvreService;
import services.VenteArtService;

/**
 *
 * @author HP
 */
public class VenteForm extends javax.swing.JInternalFrame {
     
    private ClientService cs;
     private OeuvreService os;
     private VenteArtService vs;
     private DefaultTableModel model =null;
     static int id ;
    
    public VenteForm() {
        initComponents();
        this.setTitle("Gestion des vente");
        cs = new ClientService();
        os =new OeuvreService();
        vs =new VenteArtService();
        model = (DefaultTableModel) ventes.getModel();
        loadClient();
        loadOeuvre();
        loadVenteArt();
    }

    /**
     *
     */
    public void loadClient() {
    clients.removeAllItems(); 
    for (Client c : cs.findAll()) {
        clients.addItem(c);  
    }
    }
     public void loadOeuvre() {
      oeuvres.removeAllItems(); 
       for (Oeuvre o : os.findAll()) {
        oeuvres.addItem(o);  
    }
}

    /**
     *
     */
    public void loadVenteArt(){
         model.setRowCount(0);
         for(VenteArt v :vs.findAll() ){
             model.addRow(new Object []{
                 v.getId(),
                 v.getOeuvre(),
                 v.getClient(),
                 v.getDateVente()
             });
         }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        client = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        oeuvres = new javax.swing.JComboBox();
        clients = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        addBn = new javax.swing.JButton();
        deleteBn = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        listeoeuvres = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ventes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateVente = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enregister une vente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(0, 51, 153))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Oeuvre:");

        client.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        client.setForeground(new java.awt.Color(0, 51, 255));
        client.setText("Client:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Date de vente:");

        oeuvres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oeuvresActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        addBn.setBackground(new java.awt.Color(51, 204, 0));
        addBn.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        addBn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uI/images/check_circle_17dp_1F1F1F_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        addBn.setText("Enregister");
        addBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBnActionPerformed(evt);
            }
        });

        deleteBn.setBackground(new java.awt.Color(204, 0, 0));
        deleteBn.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        deleteBn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uI/images/delete_17dp_1F1F1F_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        deleteBn.setText("Annuler");
        deleteBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBnActionPerformed(evt);
            }
        });

        modifier.setBackground(new java.awt.Color(255, 255, 51));
        modifier.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uI/images/edit_17dp_1F1F1F_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        modifier.setText("modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addBn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(addBn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(modifier)
                .addGap(55, 55, 55)
                .addComponent(deleteBn)
                .addGap(32, 32, 32))
        );

        listeoeuvres.setBackground(new java.awt.Color(255, 255, 255));
        listeoeuvres.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste des ventes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(0, 51, 102))); // NOI18N

        ventes.setBackground(new java.awt.Color(153, 153, 255));
        ventes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        ventes.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        ventes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Oeuvre", "Client", "Date de vente"
            }
        ));
        ventes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ventesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ventes);

        javax.swing.GroupLayout listeoeuvresLayout = new javax.swing.GroupLayout(listeoeuvres);
        listeoeuvres.setLayout(listeoeuvresLayout);
        listeoeuvresLayout.setHorizontalGroup(
            listeoeuvresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        listeoeuvresLayout.setVerticalGroup(
            listeoeuvresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uI/images/target-audience.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uI/images/palette (1).png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uI/images/calendar (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dateVente, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(client))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clients, 0, 272, Short.MAX_VALUE)
                            .addComponent(oeuvres, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(listeoeuvres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(oeuvres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(clients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(client))
                            .addComponent(jLabel2))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(dateVente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(listeoeuvres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oeuvresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oeuvresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oeuvresActionPerformed

    private void addBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBnActionPerformed
        // TODO add your handling code here:

        Oeuvre oeuvre = (Oeuvre) oeuvres.getSelectedItem();
        Client client = (Client) clients.getSelectedItem();
        Date datevente = dateVente.getDate();
        vs.create(new VenteArt(  oeuvre, client,datevente));
        loadVenteArt();
        vider();
    }//GEN-LAST:event_addBnActionPerformed

    private void deleteBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBnActionPerformed
        // TODO add your handling code here:

        // TODO add your handling code here:

        int reponse =JOptionPane.showConfirmDialog(this, "Voulez vous vraiment annuler ce vent ? " );
        if(reponse ==0){
            vs.delete(vs.findById(id));
            loadVenteArt();
            vider();
        }
    }//GEN-LAST:event_deleteBnActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
       int reponse = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment modifier cette vente ?");

    if (reponse == JOptionPane.YES_OPTION) {

        Oeuvre oeuvre = (Oeuvre) oeuvres.getSelectedItem();
        Client client = (Client) clients.getSelectedItem();
        Date datevente = dateVente.getDate();

        VenteArt v = new VenteArt(id, oeuvre, client, datevente);

        vs.update(v);
        loadVenteArt();
        vider();
    }
    }//GEN-LAST:event_modifierActionPerformed

    private void ventesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventesMouseClicked
        // TODO add your handling code here:
        int selectedRow = ventes.getSelectedRow();
    if (selectedRow >= 0) {

        // ID
        id = (int) ventes.getValueAt(selectedRow, 0);

        // OEUVRE
        Oeuvre selectedOeuvre = (Oeuvre) ventes.getValueAt(selectedRow, 1);
        oeuvres.setSelectedItem(selectedOeuvre);

        // CLIENT
        Client selectedClient = (Client) ventes.getValueAt(selectedRow, 2);
        clients.setSelectedItem(selectedClient);

        // DATE
        try {
            Object dateObj = ventes.getValueAt(selectedRow, 3);

            if (dateObj instanceof Date) {
                dateVente.setDate((Date) dateObj);
            } else {
                String dateStr = dateObj.toString();
                java.util.Date date = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(dateStr);
                dateVente.setDate(date);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_ventesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel client;
    private javax.swing.JComboBox clients;
    private com.toedter.calendar.JDateChooser dateVente;
    private javax.swing.JButton deleteBn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listeoeuvres;
    private javax.swing.JButton modifier;
    private javax.swing.JComboBox oeuvres;
    private javax.swing.JTable ventes;
    // End of variables declaration//GEN-END:variables

    private void vider() {
          if (oeuvres.getItemCount() > 0) {
        oeuvres.setSelectedIndex(0);
    } else {
        oeuvres.setSelectedItem(null);
    }

    if (clients.getItemCount() > 0) {
        clients.setSelectedIndex(0);
    } else {
        clients.setSelectedItem(null);
    }
    dateVente.setDate(null);
}

    }
